site_name: Server Essentials Wiki

nav:
    - Home: 'index.md'
    - Modules:
        - 'Core': 'modules/core-module'
        - 'General': 'modules/general-module'
        - 'Rank': 'modules/rank-module'
        - 'AutoRank': 'modules/autorank-module'
        - 'Language': 'modules/language-module'
        - 'Economy': 'modules/economy-module'
        - 'Security': 'modules/security-module'
        - 'Ban': 'modules/ban-module'
        - 'Discord': 'modules/discord-module'
    - Home: 'index.md'
    - 'Guides / Tutorials':
        - '': ''

markdown_extensions:
  - admonition

theme:
  name: material

  theme:
  logo: assets/logo.png
  favicon: assets/logo.png
