version=0.0.0

# Library Versions
gson_version=2.13.2
jtoml_version=1.1.1
log4j_version=2.25.2
slf4j_version=1.7.36
highscalelib_version=1.0.6
apache_io_version=2.21.0
mysql_connector_version=8.0.33
postgres_version=42.7.8
javalin_version=4.6.8
kotlin_version=1.9.25
reflections_version=0.11.7
javassist_version=3.30.2-GA
javalin_openapi_version=4.6.8
junit_version=5.14.1
discord4j_version=3.3.0
hibernate_version=5.6.5.Final