modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Wurmcraft/Server-Essentials/issues"
[[mods]]
modId="serveressentials"
version="${file.jarVersion}"
displayName="Server Essentials"
displayURL="https://www.curseforge.com/minecraft/mc-mods/server-essentials"
logoFile="se-logo.png"
credits=""
authors="Wurmatron"
description='''
Server Essentials is a mod designed to be used as a standalone server utility
 mod for server / network owners looking for an all in one solution to
 server administration. Server Essentials or SE for short is created out of
 diffrent "modules" which can be enabled / disabled based on the needs of
 the server / network owner.
'''

[[dependencies.serveressentials]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="SERVER"