site_name: Server Essentials Wiki
site_url: https://wiki.wurmatron.io/server-essentials/
theme:
  name: material
nav:
    - 'User Guide':
        - 'Getting Started': 'user-guides/getting-started'
        - 'Claiming / Protect an Area': 'user-guides/claiming'
        - 'Discord Bot': 'user-guides/discord-bot'
        - 'Trading': 'user-guides/trading'
        - 'Server Transfer': 'user-guides/server-transfer'
        - 'Ranks': 'user-guides/ranks'
    - 'Modules':
        - 'Core': 'modules/core.md'
        - 'Chat': 'modules/chat.md'
        - 'Rank': 'modules/rank.md'
        - 'Discord': 'modules/discord.md'
        - 'AutoRank': 'modules/autorank.md'
        - 'General': 'modules/general.md'
        - 'Donator': 'modules/donator.md'
        - 'Logging': 'modules/logging.md'
        - 'Economy': 'modules/Economy.md'
        - 'Transfer': 'modules/transfer.md'
        - 'Ban': 'modules/ban.md'
        - 'Statistics': 'modules/statistics.md'
        - 'Protect': 'modules/protect.md'
        - 'Security': 'modules/security.md'
        - 'Language': 'modules/language.md'
    - 'Commands': 'commands'
    - 'Setup Guide':
        - 'Getting Started': 'setup-guides/getting-started'
        - 'Creating a Rank': 'setup-guides/rank-creation'
        - 'Creating a Rankup Condition': 'setup-guides/rankup-condition'
        - 'Creating a Currency': 'setup-guides/currency-creation'
        - 'Creating a trade network': 'setup-guides/trade-network'
        - 'Creating a Custom Command': 'setup-guides/custom-command'
        - 'Discord Bot Setup': 'setup-guides/discord-setup'
        - 'Ptredactyl Intergration': 'setup-guides/ptredactyl-intergration'
    - 'Administration Guide':
        - 'Getting Started': 'admin-guides/getting-started'
        - 'Collecting Information': 'admin-guides/info-collection'
        - 'Discord Bot (User-Interactions)': 'gadmin-guides/discordbot-intergration'
        - 'Network Explination': 'admin-guides/network-explanation'
        - 'Common Issues / Fixes': 'admin-guides/common-issues'
    - 'Panel Guide':
        - 'Getting Started': 'panel-guides/getting-started.md'
    - 'Configuration':
        - 'Backend':
            - 'Internal': 'config/backend-internal'
            - 'Logs': 'config/backend-logs'
            - 'Config': 'config/backend-config'
            - 'Discord': 'config/backend-discord'
            - 'Ptredactyl': 'config/pterodactyl'
        - 'Mod':
            - 'Modules': 'config/mod-modules'
            - 'Commands': 'config/mod-commands'
            - 'General': 'config/mod-general'
            - 'Discord': 'config/mod-discord'
    - 'Links':
        - 'CurseForge': 'https://www.curseforge.com/minecraft/mc-mods/server-essentials/'
        - 'Github': 'https://github.com/Wurmcraft/Server-Essentials/'
        - 'Issues': 'https://github.com/Wurmcraft/Server-Essentials/issues/'
        - 'Ci / Nightly Builds': 'https://ci.wurmatron.io/job/Server%20Essentials/'
        - 'Donate': 'https://www.paypal.com/cgi-bin/webscr?return=https://www.curseforge.com/projects/270700&cn=Add+special+instructions+to+the+addon+author()&business=wurmatron%40wurmcraft.com&bn=PP-DonationsBF:btn_donateCC_LG.gif:NonHosted&cancel_return=https://www.curseforge.com/projects/270700&lc=US&item_name=Server+Essentials+(from+curseforge.com)&cmd=_donations&rm=1&no_shipping=1&currency_code=USD'
